const arrItems = [
    {
      id: 0,
      img: "./img/01.png",
      name: "MONTBLANC",
      price: 1900,
      currancy: "$",
      madein: "Belaurs",
    },
    {
      id: 1,
      img: "./img/02.png",
      name: "SEIKO",
      price: 1200,
      currancy: "$",
      madein: "Belarus",
    },
    {
      id: 2,
      img: "./img/03.png",
      name: "ORIENT",
      price: 1000,
      currancy: "$",
      madein: "Belarus",
    },
    {
      id: 3,
      img: "./img/04.png",
      name: "SWAROVSKI",
      price: 1900,
      currancy: "$",
      madein: "Belarus",
    },
    {
      id: 4,
      img: "./img/05.png",
      name: "ROLEX",
      price: 1900,
      currancy: "$",
      madein: "Belarus",
    },
  ];